language: node_js
cache:
  directories:
  - ~!@/.npm
node_js:
  - '8'
git:
  depth: 3
script:
  - yarn build
  // - echo 'url-personalizada.com' > pubic/CNAME
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: dist/
  target-branch: master
  commit_message: "Deploy release ${TRAVIS_TAG}"
on:
  branch: devel